### ISSUE TITLE
How can I get all of the bounds when the interval is not atomic?

### ISSUE THREAD

**Issue by im-fancy** [AlexandreDecan/portion#32]
Dear author，

Thank you for your excellent work! I have a question:

 when the interval is not atomic, eg, 

x = P.open(0, 1) | P.closed(3, 4)

I can use x.lower and x.upper get 0 and 4. Which attribute can I use to access 1 and 3?

**Comment by AlexandreDecan** [comment]
Hello,

You can iterate on an interval to get access to the underlying atomic intervals:

```
>>> x = P.open(0, 1) | P.closed(3, 4)
>>> for i in x: 
       print(i.lower, i.upper)
0 1
3 4
```

**Comment by im-fancy** [comment]
Many thanks!

**Comment by AlexandreDecan** [comment]
You're welcome ;-)
