### ISSUE TITLE
Impossible to set closed interval bounds explicitly with replace

### ISSUE THREAD

**Issue by TimBergner** [AlexandreDecan/portion#40]
Other than specified in the documentation it is impossible to set closed interval bounds explicitly with `replace` (at least I can't). When an interval boundary is closed, it remains closed unless you want to set it explicitly closed.
Example:
```python
>>> i = P.closedopen(0, 2)
>>> i.replace()
[0,2)
>>> i.replace(left=P.CLOSED)
(0,2)
>>> i.replace(left=lambda v: P.CLOSED)
(0,2)
>>> i.replace(lower=1)
[1,2)
```

**Comment by AlexandreDecan** [comment]
Hello,

Could you tell me which version of `portion` you're using? When I execute your code snippet, I got: 

```python
>>> i = P.closedopen(0, 2)
>>> i.replace()
[0,2)
>>> i.replace(left=P.CLOSED)
[0,2)
>>> i.replace(left=lambda v: P.CLOSED)
[0,2)
>>> i.replace(lower=1)
[1,2)

```

... which is the desired behaviour. 

Thanks

**Comment by TimBergner** [comment]
Ups. I can't reproduce the behavior now in a new instance of the IPython console. So I probably overwrote some variables or something like that.

Sorry for this issue! Even if the error was reproducible also after reloading `portion` while running the same iPython instance, I should have tested it again in a new instance - my fault.

**Comment by AlexandreDecan** [comment]
Don't worry ;) I'm glad it's not a new bug :-)
