### ISSUE TITLE
Conda-forge fail due to dependency

### ISSUE THREAD

**Issue by egemenimre** [AlexandreDecan/portion#46]
Hallo,

I have bumped the version of _satmad_, my library that depends on portion. Conda-forge process failed with the following error:

> portion 2.1.3 has requirement sortedcontainers~=2.2.2, but you have sortedcontainers 2.3.0.

Looks like there is a hard dependency on a specific version of sortedcontainers. Is this strictly necessary? Is there any issue with a specific version  of it?

Cheers!

**Comment by AlexandreDecan** [comment]
Hello,I guess we can change this to >=2.2.0 and <3.0.0. There is no hard constraint on 2.2.x. Sortedcontainer is stable enough not to release a breaking change in the 2.x.x branch I guess. Can I ask you to submit a PR for this? Thanks! Le 12 nov. 2020 8:22 PM, Egemen Imre <notifications@github.com> a écrit :
Hallo,
I have bumped the version of satmad, my library that depends on portion. Conda-forge process failed with the following error:

portion 2.1.3 has requirement sortedcontainers~=2.2.2, but you have sortedcontainers 2.3.0.

Looks like there is a hard dependency on a specific version of sortedcontainers. Is this strictly necessary? Is there any issue with a specific version  of it?
Cheers!

**Comment by egemenimre** [comment]
Done. Let's hope it doesn't bounce back from Travis. :)

**Comment by AlexandreDecan** [comment]
Thanks for the PR! I released 2.1.3-post1 with the soften dependency constraint. 
It should be "official" in a few minutes, as soon as Travis finishes :)
