### ISSUE TITLE
Any interval contains the empty interval

### ISSUE THREAD

**Issue by simon-keith** [AlexandreDecan/portion#48]
```python
import portion as p

print(p.closed(0, 1).contains(p.empty()))
```

The above prints `True`, meaning than any interval contains the empty interval. Is that intended?

**Comment by simon-keith** [comment]
I think it actually makes sense mathematically, I just wanted to make sure.

**Comment by AlexandreDecan** [comment]
Hello,

You're right, the empty interval is contained in all (possibly empty as well) intervals, by definition.

**Comment by simon-keith** [comment]
Ok, thank you for clarifying!
