### ISSUE TITLE
Chinese-version documentation. (已添加中文文档)

### ISSUE THREAD

**Issue by longqh3** [AlexandreDecan/portion#55]
Nice library and it saved my great efforts to manipulate between intervals.
During my process of getting to learn about your library, I wrote down a Chinese version documentation ([CSDN link](https://blog.csdn.net/believerto/article/details/114935671), maybe naive, but enough to know basic usage and advanced operations) which attached to this comment.
Hope can be of little help to our Chinese users. Again, thanks for your nice library and hope more coders can know about it. 

[portion-doc-zh_CN.zip](https://github.com/AlexandreDecan/portion/files/6158231/portion-doc-zh_CN.zip)

**Comment by AlexandreDecan** [comment]
Thank you for the nice feedback, and thank you for the work you've done for this translation! 

In order to allow other users to benefit from it I'll keep this issue open and add a specific label so it will be easier to find it.

**Comment by AlexandreDecan** [comment]
Hello @longqh3 

Is the Chinese-version of the documentation still up-to-date with the "recent" changes that were introduced these last 2 years? 
See version 2.2.0 (https://github.com/AlexandreDecan/portion/blob/master/CHANGELOG.md#220-2021-09-14), 2.3.0 (https://github.com/AlexandreDecan/portion/blob/master/CHANGELOG.md#230-2022-08-31) and 2.4.0 (https://github.com/AlexandreDecan/portion/blob/master/CHANGELOG.md#240-2023-03-13).

I'm not saying it should be completed, but perhaps some of the changes we introduced in these versions affect your Chinese-version of the documentation.... :-) 

Thank you!

**Comment by AlexandreDecan** [comment]
Closing this issue since @longqh3 seems to have disappeared from GitHub :-)
