### ISSUE TITLE
Ordering problem in intervals

### ISSUE THREAD

**Issue by jefftrull** [AlexandreDecan/portion#64]
Intervals implement the special comparison methods, but in some corner cases they behave in surprising ways:

```python
import portion as P

a = P.openclosed(0, 1)
b = P.closedopen(1, 2)

print(b > a)
print(b == a)
print(b >= a)

```
prints:
```
False
False
True
```

Similarly,
```python
print(a < b)
print(a == b)
print(a <= b)
```
prints
```
False
False
True
```

This violates the expectation that `(x >= y) == ((x > y) or (x == y))`.

In my view the right fix is to make each of the first expressions above - that is, `b > a` and `a < b` - return true for these cases.

**Comment by AlexandreDecan** [comment]
Hello, 

While it may seem incorrect, this is the expected behaviour of comparison operators. As stated in the documentation (see https://github.com/AlexandreDecan/portion#comparison-operators):

> Moreover, intervals are comparable using >, >=, < or <=. These comparison operators have a different behaviour than the usual ones. For instance, a < b holds if a is entirely on the left of the lower bound of b and a > b holds if a is entirely on the right of the upper bound of b. [...] Similarly, a <= b holds if a is entirely on the left of the upper bound of b, and a >= b holds if a is entirely on the right of the lower bound of b. [...] Note that all these semantics differ from classical comparison operators. As a consequence, some intervals are never comparable in the classical sense.

**Comment by jefftrull** [comment]
Wow! OK, thanks. I missed that part in the docs.

**Comment by AlexandreDecan** [comment]
No problem ;-)
