### ISSUE TITLE
Is this library performant enough to work with (non-atomic) intervals which span integers between 1 and 1 billion?

### ISSUE THREAD

**Issue by sameerbharatia** [AlexandreDecan/portion#73]
This will involve unions, differences, intersections etc. etc. Will this library be able to do lots of computations like this for large spanning **(non-atomic)** intervals quickly?

**Comment by AlexandreDecan** [comment]
Hello,

It should ;-) Performance is mostly dependent on the number of atomic intervals in the non-atomic ones, and does not depend on the values being used for their bounds.
