### ISSUE TITLE
Add join / merge method

### ISSUE THREAD

**Issue by evyasonov** [AlexandreDecan/portion#80]
Hi
Thank you for this great module
Can you please add a method to join a list of intervals the followin way:
```
portion.or_join(portion.open(i*10, i*10+1) for i in range(5))
```
It will be extreamly helpful
Thanks in advance

**Comment by AlexandreDecan** [comment]
You can already achieve the same result with `portion.Interval(*[portion.open(i*10, i*10+1) for i in range(5)])`. 
More generally, you can rely on the `operator` module and the `reduce` function to achieve the same result. For example, 

```python
>>> from operator import or_
>>> from functools import reduce
>>> intervals = [portion.open(i*10, i*10+1) for i in range(5)]
>>> result = reduce(or_, intervals)
```

**Comment by evyasonov** [comment]
Got it! Thank you for the answer
