### ISSUE TITLE
"compatible version" specifier in setup.py confuses poetry

### ISSUE THREAD

**Issue by burnpanck** [AlexandreDecan/portion#81]
The documentation and the "Classifiers" inside `setup.py` seem to indicate that `portion` is supposed to support python 3.7 **and up.**

However, `setup.py` also specifies `python_requires="~=3.7"`, which, according to canonical [SemVer (or node.js really)](https://docs.npmjs.com/cli/v6/using-npm/semver#tilde-ranges-123-12-1) only allows patch-level upgrades. [PEP440](https://peps.python.org/pep-0440/#compatible-release) on the other hand says it is equivalent to `>=3.7,==3.*` which I believe is what you intend. Unfortunately, it seems that poetry [currently misinterprets that specification](https://github.com/python-poetry/poetry/issues/7656).

Given that the two specifications differ in their interpretation of the `~=` specification, it may be wise to simply use `>=3.7,==3.*` directly. Explicit is better than implicit.

**Comment by AlexandreDecan** [comment]
I like self-resolving issues ;-)
