### ISSUE TITLE
Error to import interval, inf, imath from interval

### ISSUE THREAD

**Issue by ankit396** [AlexandreDecan/portion#86]
Hello, 

I am unable to import interval, inf, imath from interval.  

![Interval1](https://github.com/AlexandreDecan/portion/assets/90715218/ab9bcac6-7298-4f92-9e73-fff3a14dc7f6)

This is the error I receive. 

![Interval2](https://github.com/AlexandreDecan/portion/assets/90715218/b7bc3d22-11e4-4e89-914d-ae2817f799c6)

**Comment by AlexandreDecan** [comment]
Hello,

This error is not related to portion.
