### ISSUE TITLE
importlib.machinery error with create_api

### ISSUE THREAD

**Issue by bulletmark** [AlexandreDecan/portion#87]
This is essentially same issue as issue #85. I get the following error:
```
$ venv/bin/python ./p05
Traceback (most recent call last):
  File "/home/mark/Data/comps/aoc/2023/./p05", line 8, in <module>
    P = portion.create_api(IntInterval)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mark/Data/comps/aoc/2023/venv/lib/python3.12/site-packages/portion/api.py", line 66, in create_api
    importlib.machinery.ModuleSpec(module_name, None)
    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'importlib' has no attribute 'machinery'
```

This is using portion 2.4.1 and happens on Python versions 3.10, 3.11, 3.12 but it does not happen with Python 3.9 where it works fine.

The fix for #85 was to add `import importlib.util`. I find here that adding `import importlib.machinery` fixes this issue.

**Comment by AlexandreDecan** [comment]
Thanks for reporting this issue! I'll have a look at it soon :-)

**Comment by AlexandreDecan** [comment]
For "posterity": more information about why this bug happens https://discuss.python.org/t/python3-11-importlib-no-longer-exposes-util/25641/21

I'm going to release a hot fix for this today (portion 2.4.2). In the meantime, you can `import importlib.machinery` in your own code before calling `creating_api` ;-)

**Comment by bulletmark** [comment]
@AlexandreDecan can you please add the discussions tab to this repo?

**Comment by AlexandreDecan** [comment]
I tend to prefer discussing in issues (to "centralise" everything). Are there extra features in the discussion tab compared to traditional issues? Le 6 déc. 2023 10:57, Mark Blakeney ***@***.***> a écrit :
@AlexandreDecan can you please add the discussions tab to this repo?

**Comment by bulletmark** [comment]
I would like to discuss something completely unrelated to this present issue but certainly not worthy of an issue. Discussions are "lightweight issues" which encourage more liberal dialog and wider participation.

**Comment by AlexandreDecan** [comment]
Thanks! 

I looked at how GitHub sells "Discussions" and, to be honest, I'm not really convinced :-) I prefer not to multiply the communication channels for this repository, for simplicity and personal preference ;-) 

If you don't mind, please open an issue (and I'll add the "discussion" label on it) or, if you prefer, you can contact me by e-mail (but I usually consider that discussions/questions/etc. should be "public" if they can benefit to other people as well :-) Perhaps I'll change my mind and I'll convert the issue to a "discussion thread" afterwards :-p
