### ISSUE TITLE
Empty Calculation Bug

### ISSUE THREAD

**Issue by Albuser** [AlexandreDecan/portion#89]
```py
myInterval = P.open(0, 1)

print(myInterval.empty)  # False
```

**Comment by Albuser** [comment]
Seems to be the same underlying problem as my other [issue](https://github.com/AlexandreDecan/portion/issues/88)

**Comment by Albuser** [comment]
Never mind, I'm being silly and considering these as integers when there's no guaranteed type

**Comment by AlexandreDecan** [comment]
No problem ;-)
