### ISSUE TITLE
The performance issues of interval calculations in large quantities.

### ISSUE THREAD

**Issue by hubuxiaohe** [AlexandreDecan/portion#91]
In my analysis, there may be a large number of intervals involved. When I traverse a large number of intervals to determine if they overlap with other intervals, the time complexity is O(n^2). However, if interval trees are used for overlap detection, the complexity becomes O(nlogn). Does the underlying principle of this module involve the use of interval trees or other suitable data structures? :)

**Comment by AlexandreDecan** [comment]
Hello,

There are several optimizations especially to handle large disjunctions of intervals. I would say: try it and see whether the performances meet your expectations or not :-)
