### ISSUE TITLE
mass/Lebesgue measure?

### ISSUE THREAD

**Issue by rytis-paskauskas** [AlexandreDecan/portion#92]
It would be useful to allow some measure theoretic operations, such as adding up masses on intervals. I think that mass could be implemented as a value of `IntervalDict`. What about mass addition?

**Comment by AlexandreDecan** [comment]
I briefly looked at interval masses and this seems quite specific to real number based intervals. I'm unsure this should fit in portion that aims to stay generic.

**Comment by rytis-paskauskas** [comment]
Not sure I can provide a useful link. Here is what I have in mind: if `I1`, `I2` are intervals, and `'mass'[I1]=m1` and `'mass'[I2]=m2`, then `dict[I1]=m1` and `dict[I2]=m2` if `I1` and `I2` are disjoint, otherwise `dict[I1\I2]=m1`, `dict[I2\I1]=m2`, and `dict[ I1 x I2]=m1+m2` if they overlap.

**Comment by rytis-paskauskas** [comment]
The current behavior of `IntervalDict` upon insertion seems to change the existing keys if there are overlaps. My suggestion is to add new behavior or modify the existing one in such a way that separates the overlapping intervals into separate keys, and that handles the values as illustrated in my previous comment. This is in line with existing behavior that does not preserveleft-constness (keys).  But it would add, I think, functionality that would be attractive for probability-related calculations.

**Comment by rytis-paskauskas** [comment]
after all, Python allows this `'orange' + 'banana'`.

**Comment by AlexandreDecan** [comment]
Please have a look at the "combine" method. It handles the example your provided.

**Comment by AlexandreDecan** [comment]
Perfect :-)
