### ISSUE TITLE
Value out of range

### ISSUE THREAD

**Issue by Dezorgon** [AlexandreDecan/portion#94]
There are several cases where using `datetime.date.min` is more convenient instead of `-intervals.inf`

When we try to run this code snippet we get a date overflow error:
`~intervals.closed(datetime.date.min, datetime.date.max)`
Result:
`OverflowError: date value out of range`

**Comment by AlexandreDecan** [comment]
Where's the question / problem?

**Comment by AlexandreDecan** [comment]
Could you clarify the problem, the expected behaviour and its rationale?

**Comment by AlexandreDecan** [comment]
No answer, no details, no public profile... Let me close this issue for now, and we'll see what will happen.
